version: "3.8"

services:
  glpi:
    image: sdbrasil/glpi:10.0.17
    container_name: glpi-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      GLPI_DB_HOST: mysql-app
      GLPI_DB_PORT: 3306
      GLPI_DB_NAME: glpi_db
      GLPI_DB_USER: glpi_user
      GLPI_DB_PASSWORD: sua_senha_forte
    volumes:
      - glpi_documents:/var/lib/glpi/files/data-documents
      - glpi_imagens_custom:/usr/share/glpi/pics/imagens-custom
      - glpi_plugins:/usr/share/glpi/plugins
      - glpi_pictures:/var/lib/glpi/files/_pictures
      - glpi_plugins_files:/var/lib/glpi/files/_plugins
      - glpi_etc:/etc/glpi/
      - glpi_backup:/backup/
    networks:
      - glpi_network

networks:
  glpi_network:
    external: true
    name: mysql_network  # Use o nome da rede do seu MySQL

volumes:
  glpi_documents:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/glpi-app/documents
  glpi_imagens_custom:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/glpi-app/imagens-custom
  glpi_plugins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/glpi-app/plugins
  glpi_pictures:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/glpi-app/files/_pictures
  glpi_plugins_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/glpi-app/files/_plugins
  glpi_etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/glpi-app/etc
  glpi_backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /dados/data/glpi/backup
