services:
  glpi:
    image: sdbrasil/glpi:10.0.19
    container_name: glpi-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      GLPI_DB_HOST: mysql-app
      GLPI_DB_PORT: 3306
      GLPI_DB_NAME: glpi_db
      GLPI_DB_USER: glpi_user
      GLPI_DB_PASSWORD: sua_senha_forte
    volumes:
      - glpi_config:/etc/glpi
      - glpi_documents:/var/lib/glpi/files/data-documents
      - glpi_plugins:/usr/share/glpi/plugins
      - glpi_marketplace:/usr/share/glpi/marketplace
      - glpi_files_plugins:/var/lib/glpi/files/_plugins
      - glpi_backup:/backup
    networks:
      - glpi_network

networks:
  glpi_network:
    external: true
    name: mysql_network  # Use o nome da rede do seu MySQL

volumes:
  glpi_config:
  glpi_documents:
  glpi_plugins:
  glpi_marketplace:
  glpi_files_plugins:
  glpi_backup:
